/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica2;

import ArbolBinarioBusquedaAVL.ArbolAVL;
import ArbolBinarioBusquedaAVL.NodoAVL;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Liceo_2
 */
public class JFPractica2 extends javax.swing.JFrame {

    boolean primeraP = false;
    public ArbolAVL diccionario;

    /**
     * Creates new form JFPractica2
     */
    public JFPractica2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        simple = new javax.swing.JButton();
        completa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cantidad = new javax.swing.JTextArea();
        textPalabra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        significadoP = new javax.swing.JButton();
        sinonimoP = new javax.swing.JButton();
        antonimoP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textARespuesta = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        importar = new javax.swing.JButton();
        exportar = new javax.swing.JButton();
        modificarP = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        DataP = new javax.swing.JTextField();
        Mostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Diccionario:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Añadir Palabra :  ");

        simple.setText(" Simple");
        simple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleActionPerformed(evt);
            }
        });

        completa.setText("Completa");
        completa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Resultado:");

        jLabel5.setText("Cantidad de palabras :");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        cantidad.setEditable(false);
        cantidad.setColumns(20);
        cantidad.setRows(5);
        jScrollPane1.setViewportView(cantidad);

        textPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPalabraActionPerformed(evt);
            }
        });

        jLabel2.setText("Palabras: ");

        significadoP.setText("Significado");
        significadoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                significadoPActionPerformed(evt);
            }
        });

        sinonimoP.setText("Sinónimos");
        sinonimoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinonimoPActionPerformed(evt);
            }
        });

        antonimoP.setText("Antónimos");
        antonimoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antonimoPActionPerformed(evt);
            }
        });

        textARespuesta.setEditable(false);
        textARespuesta.setColumns(20);
        textARespuesta.setRows(5);
        jScrollPane2.setViewportView(textARespuesta);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Busquedas:");

        importar.setText("   Importar Diccionario");
        importar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                importarMouseClicked(evt);
            }
        });
        importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarActionPerformed(evt);
            }
        });

        exportar.setText(" Exportar  Diccionario");
        exportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exportarMouseClicked(evt);
            }
        });

        modificarP.setText("Modificar Esta Palabra");
        modificarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPActionPerformed(evt);
            }
        });

        jButton1.setText("Cantidad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        DataP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPActionPerformed(evt);
            }
        });

        Mostrar.setText("Mostrar");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(modificarP)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(importar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exportar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(DataP, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(simple)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(completa))
                                .addComponent(jScrollPane2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(textPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40)
                                            .addComponent(significadoP)
                                            .addGap(18, 18, 18)
                                            .addComponent(sinonimoP))
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(antonimoP))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Mostrar)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(321, 321, 321)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                .addGap(1, 1, 1)))))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jLabel6)
                    .addContainerGap(546, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simple)
                            .addComponent(completa)
                            .addComponent(DataP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(significadoP)
                    .addComponent(sinonimoP)
                    .addComponent(antonimoP))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importar)
                    .addComponent(exportar))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPalabraActionPerformed

    private void sinonimoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinonimoPActionPerformed
        NodoAVL aux;
        aux = diccionario.buscarComplejo(textPalabra.getText(), 0);
        if (aux != null) {
            textARespuesta.setText(diccionario.Mostrar(1));
        } else {
            textARespuesta.setText("La palabra no existe en el diccionario");
        }
    }//GEN-LAST:event_sinonimoPActionPerformed

    private void significadoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_significadoPActionPerformed
        NodoAVL aux;
        aux = diccionario.buscarComplejo(textPalabra.getText(), 0);
        if (aux != null) {
            if (aux.getSignificado() != "") {
                textARespuesta.setText(aux.getSignificado());
            } else {
                textARespuesta.setText("La palabra no tiene significado agregado aun");
            }
        } else {
            textARespuesta.setText("La palabra no existe en el diccionario");
        }
    }//GEN-LAST:event_significadoPActionPerformed

    private void importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarActionPerformed

    }//GEN-LAST:event_importarActionPerformed

    private void antonimoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antonimoPActionPerformed
        NodoAVL aux;
        aux = diccionario.buscarComplejo(textPalabra.getText(), 0);
        if (aux != null) {
            textARespuesta.setText(diccionario.Mostrar(2));
        } else {
            textARespuesta.setText("La palabra no existe en el diccionario");
        }
    }//GEN-LAST:event_antonimoPActionPerformed

    private void completaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completaActionPerformed
        NodoAVL aux;
        String palabra = DataP.getText();
        if (!palabra.equals("") && diccionario != null) {
            NodoAVL prueba = new NodoAVL(DataP.getText());
            if (diccionario.buscarComplejo(prueba.getDato(), 0) == null) {
                aux = diccionario.insertarPalabraS(DataP.getText());
                diccionario.InsertarPalabraC(aux);
            } else if (prueba.getSignificado() == null || prueba.getSinonimo() == null || prueba.getAntonimo() == null) {
                prueba = diccionario.buscarComplejo(prueba.getDato(), 0);
                diccionario.InsertarPalabraC(prueba);
            } else {
                JOptionPane.showMessageDialog(null, "Esta palabra ya existe");
            }
        } else {
            if (diccionario == null) {
                JOptionPane.showMessageDialog(null, "Error, recuerde importar los archivos");
            } else {
                JOptionPane.showMessageDialog(null, "Error, espacio en blanco no permitido");
            }

        }

        textPalabra.setText("");
    }//GEN-LAST:event_completaActionPerformed


    private void simpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleActionPerformed
        try {
            String palabra = DataP.getText();
            if (!palabra.equals("") && diccionario != null) {
                if (diccionario.buscarComplejo(DataP.getText(), 0) == null) {
                    diccionario.insertarPalabraS(DataP.getText());
                } else {
                    JOptionPane.showMessageDialog(null, "Esta palabra ya existe");
                }
            } else {
                if (diccionario == null) {
                    JOptionPane.showMessageDialog(null, "Error, recuerde importar los archivos");
                } else {
                    JOptionPane.showMessageDialog(null, "Error, espacio en blanco no permitido");
                }
            }
            textPalabra.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algo salio mal");
        }
    }//GEN-LAST:event_simpleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cantidad.setText("" + diccionario.getCantidadp());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DataPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataPActionPerformed

    private void importarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_importarMouseClicked
        try {
            diccionario = new Diccionario(textARespuesta);
            if (diccionario != null) {
                cantidad.setText(diccionario.getCantidadp() + "");
            }
        } catch (IOException ex) {
            textARespuesta.setText(ex.getLocalizedMessage());
        } catch (Exception ex) {
            Logger.getLogger(JFPractica2.class.getName()).log(Level.SEVERE, null, ex);
        }
        importar.setEnabled(false);
    }//GEN-LAST:event_importarMouseClicked

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        if(diccionario!=null){
            textARespuesta.setText(diccionario.Mostrar(0));
        }else{
            JOptionPane.showMessageDialog(null, "El diccionario esta vacio");
        }

    }//GEN-LAST:event_MostrarActionPerformed

    private void exportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exportarMouseClicked

    }//GEN-LAST:event_exportarMouseClicked

    private void modificarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPActionPerformed
        NodoAVL nodoE = diccionario.buscarComplejo(textPalabra.getText(),0);
        if(nodoE!=null){
            diccionario.Modificar(nodoE);
        }else if(diccionario==null){
            JOptionPane.showMessageDialog(null, "El diccionario esta vacio");
        }else{
            JOptionPane.showMessageDialog(null, "La palabra No existe en el diccionario");
        }
    }//GEN-LAST:event_modificarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPractica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPractica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPractica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPractica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPractica2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DataP;
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton antonimoP;
    private javax.swing.JTextArea cantidad;
    private javax.swing.JButton completa;
    private javax.swing.JButton exportar;
    private javax.swing.JButton importar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton modificarP;
    private javax.swing.JButton significadoP;
    private javax.swing.JButton simple;
    private javax.swing.JButton sinonimoP;
    private javax.swing.JTextArea textARespuesta;
    private javax.swing.JTextField textPalabra;
    // End of variables declaration//GEN-END:variables
}
